language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - echo "skipping tests"
deploy:
  provider: pypi
  user: travis_ci
  distributions: sdist bdist_wheel
  password:
    secure: HuS7Qd7yh/+0P7bU1MeaPiUGw1fl6KGtGX3rSIDs0mo4gTawhgS+LQ/wxOH4ZYr+/XSDD/zEMLEkvHBKy+VWAaVnxU0ZY85N5FLxT3mmDd0szehPbVfAdNpjtNkF+8fHEbffFnE5AMECXghgiguOsw6FB8Wh4f7zSRCv5yCpZamtkiKrzTVJGOGcld+k3KJqKaWdxGeZ7AgOs5ECRmSWkUvB+BDdQs//BowIyRnOGCqBTwn9TAIv8Qm7fIRFaVr3ZVmp8W1xxRxL4iSaE/ez3OBWh3hWz2EzKDQQF2raloKzNhfDRitthhjXz+hjTjiVi+OKmC46pFncenItRtCTL76dsVM38Yvv5Rgwr50XLv68dBL0MFkdvbCVi/CtYdMnSGVJxX9E3XsDHclKBSxZPI89NlY/VE8DSP80pELVf7waE74j3PfkyuKJYX0/GhdJ14+HzOpGv3dTriGWrLsUYYj+4Uu5r/kAxr984CFYlVoscWkrJVw+DbSmle+1xpZ92PnHnG+P3PIUSzeonWtY8vA8O+5bzH7+aCdb1lrACig01S6KfKUdXkAOzajJy4nc6gH6zgOp7ZvpozCUDt4S/+iRjaqRsKqHCnnvvAF74wS9hQJsaNLZO76O4KXUQ5kNnNtQn0vWRdP3VNZuH7U33i5plSSenFi/aruPiDqNEOI=
  on:
    branch: master