language: python
python:
  - '3.7'
  - '3.8'
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - echo "skipping tests"
deploy:
  provider: pypi
  user: travis_ci
  distributions: sdist bdist_wheel
  on:
    branch: master
  password:
    secure: jVl3KOMBRdEfnDTRVduvpoE7FvzKXsLhjQt93vl9aG42OJjczYADeS4s3o7MOD8asT1a1umTk645PK4XKcIG5j1uORZIRMqwWIzl7fFaq4k06JQ2KvBl69lwNEsTxxWSGwtoHBPq0eeiaOw0UBZMw/daybNr3AexAFOqcu8osc94i30NEomkkFph51URaASje34/to2B7zsAi3NfltzTz1bK5nw2nznry5S5LfD1qCF8u8EWBn99rhLG+qzuMTj8QLL9bDxQoXwT8pLOYgPKsYN1Vzw862mtiGEWoPm6zcwTzCwOgZ/lLTqhfH3hqvOSS2lZ55TWCSfVVsuK76DFZ6rGaR9bYLDFz785lDBZcjr2jiuK8V8NeMsVOR062ZxVKS9P+4WNTSmCD9jVtCoO4NSz+oNhg5SXjMMSunhi4sds5CrIQ8r9cI5A9WKJecFYVuZ4lLLWhU3J8lQVQLyPFFO2esUVz+DA40vIgUClP/wmL1hqnmO15Co//mbMduA8ZqQJzt7gA8h+f2WB8xm7Do7SSRErurbv6A+fqIxQoVntDVBCcrvRVJZN/Qph329vdWOc1TJ02qXW2yUnnzgLVgw2ps7TvfgaLDEdbvFeGErHfC1i77sMYgGXVA5sG22Ux8jao6H9sLM8nT4sLf0RFN6mnyddQoSkwfnbMnaqmkg=
